networks:
  xennet:
    name: xennet
    external: true

services:
  xentrack-dash:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GEMINI_API_KEY: ${GEMINI_API_KEY:-}
    image: xentrack-dash:2.0
    container_name: xentrack-dash
    networks:
      - xennet
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
